Add Kaiko dataset
iExecBlockchainComputing/iexec-datasets-registry pull request #12
Opened 2019-07-02 09:17 UTC by Legogris

2019-07-18 09:10 UTC, PierreJeanjacquot requested changes
Hi Robert,
It looks like you forgot to set `datasetMultiaddr` in `iexec.json` before running `iexec dataset deploy`.
```
iexec dataset show 0x3a85Ff58BB3eFA3d02339BF74b3c77C22b5eA08F --chain 42
ℹ using chain [kovan]
✔ dataset 0x3a85Ff58BB3eFA3d02339BF74b3c77C22b5eA08F details:
datasetName:      kaiko-trades-mtgox
datasetChecksum:  0x0000000000000000000000000000000000000000000000000000000000000000
owner:            0xA5581e22e7E80cDA4B10E6dD99F5E59e914D15e1
datasetMultiaddr: /ipfs/QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ
```
You can fix `datasetMultiaddr` in your local `iexec.json` then run `iexec dataset deploy` to get a new dataset address.
Make sure to push the dataset secret and publish orders before editing the `deplyed.json` in your PR.

2019-09-03 14:14 UTC, Legogris commented
@PierreJeanjacquot Good catch! Edited and redeployed - did I get it right this time?

2019-09-04 11:41 UTC, PierreJeanjacquot commented
@Legogris your dataset is deployed but no order is published and the secret for decryption is missing.

To push the secret in the secret management system, please run:
```
iexec tee push-secret --dataset 0x3074822604c414bB4dBA9F23E8E8355a98EfE4b9 --secret-path <secretPath>
# check the secret is pushed
iexec tee check-secret 0x3074822604c414bB4dBA9F23E8E8355a98EfE4b9
```

To publish your datasetorder:
```
iexec order init --dataset
# edit  order.datasetorder in 'iexec.json' to custom your order
iexec order sign --dataset
iexec order publish --dataset
# check the published order for your dataset
iexec orderbook dataset 0x3074822604c414bB4dBA9F23E8E8355a98EfE4b9
```

2021-06-25 23:36 UTC, cryptoloewe approved these changes

2022-11-11 22:25 UTC, closed without merging